# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/seba/Workspace/projects/rp_vv/project/project.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0.xci
# IP: The module: 'system_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/seba/Workspace/projects/rp_vv/project/project.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/seba/Workspace/projects/rp_vv/project/project.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0.xci
# IP: The module: 'system_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/seba/Workspace/projects/rp_vv/project/project.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
