# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/seba/Workspace/projects/rp_vv/dev_4/dev_4.srcs/sources_1/bd/system/ip/system_vv_model_2_0_0/system_vv_model_2_0_0.xci
# IP: The module: 'system_vv_model_2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/seba/Workspace/projects/rp_vv/dev_4/dev_4.srcs/sources_1/bd/system/ip/system_vv_model_2_0_0/vv_model_2_mult_gen_v12_0_i0/vv_model_2_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vv_model_2_mult_gen_v12_0_i0 || ORIG_REF_NAME==vv_model_2_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: /home/seba/Workspace/projects/rp_vv/dev_4/dev_4.srcs/sources_1/bd/system/ip/system_vv_model_2_0_0/constrs/vv_model_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_vv_model_2_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/seba/Workspace/projects/rp_vv/dev_4/dev_4.srcs/sources_1/bd/system/ip/system_vv_model_2_0_0/system_vv_model_2_0_0.xci
# IP: The module: 'system_vv_model_2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/seba/Workspace/projects/rp_vv/dev_4/dev_4.srcs/sources_1/bd/system/ip/system_vv_model_2_0_0/vv_model_2_mult_gen_v12_0_i0/vv_model_2_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vv_model_2_mult_gen_v12_0_i0 || ORIG_REF_NAME==vv_model_2_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: /home/seba/Workspace/projects/rp_vv/dev_4/dev_4.srcs/sources_1/bd/system/ip/system_vv_model_2_0_0/constrs/vv_model_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_vv_model_2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
